// End-to-end testing to test application if it works as intended
// May create scripts, in this case, making sure you have USDC in your account
// On the otherhand, unit testing is to test your contract functions and working as intended
// Don't mis your testing together, they are separate.
// This is to not over complicate your scripts, helps reduce human error with your testing


// Contracts
const Land = artifacts.require("Land")
const IERC20 = artifacts.require("./IERC20")

// Utils
const ether = (n) => {
    return new web3.utils.BN(
      web3.utils.toWei(n.toString(), 'ether')
    )
  }

  // Change COST to AMOUNT
  const AMOUNT = web3.utils.toWei('100', 'mwei')
  const USDC = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  const UNLOCKED_ACCOUNT = '0x72a53cdbbcc1b9efa39c834a540550e23463aacb' // USDC Unlocked Account
  
  // Declare and define, got rid of land, result, and owner2
  let usdc, receiver
  receiver = web3.eth.getAccounts();

module.exports = async function(callback) {
    // TODO: implement your actions
    try {
        // Get access to our ganache account
        const accounts = await web3.eth.getAccounts()

        // Assign receiver to the first account generated by ganache
        const receiver = accounts[0]

        // UNLOCKED_ACCOUNT transfers USDC to receiver
        await usdc.transfer(receiver, AMOUNT, { from: UNLOCKED_ACCOUNT })
    }
    
	console.log(`USDC Transferred ${AMOUNT} from ${UNLOCKED_ACCOUNT}`);
	
	callback();
}
  